{{/*
Copyright 2017 The Openstack-Helm Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}

{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.db_init }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: maas-db-init
spec:
  template:
    metadata:
      labels:
{{ tuple $envAll "maas" "db-init" | include "helm-toolkit.snippets.kubernetes_metadata_labels" | indent 8 }}
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        {{ .Values.labels.region.node_selector_key }}: {{ .Values.labels.region.node_selector_value }}
      initContainers:
{{ tuple $envAll $dependencies "[]" | include "helm-toolkit.snippets.kubernetes_entrypoint_init_container" | indent 8 }}
      containers:
        - name: maas-db-init
          image: {{ .Values.images.db_init | quote }}
          imagePullPolicy: {{ .Values.images.pull_policy | quote }}
{{ tuple $envAll $envAll.Values.pod.resources.jobs.db_init | include "helm-toolkit.snippets.kubernetes_resources" | indent 10 }}
          env:
            - name: ROOT_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.maas_db.admin }}
                  key: DATABASE_USERNAME
            - name: ROOT_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.maas_db.admin }}
                  key: DATABASE_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.maas_db.user }}
                  key: DATABASE_HOST
            - name: USER_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.maas_db.user }}
                  key: DATABASE_USERNAME
            - name: USER_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.maas_db.user }}
                  key: DATABASE_PASSWORD
            - name: USER_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.maas_db.user }}
                  key: DATABASE_NAME
          command:
            - /tmp/db-init.sh
          volumeMounts:
            - name: maas-bin
              mountPath: /tmp/db-init.sh
              subPath: db-init.sh
              readOnly: true
      volumes:
        - name: maas-bin
          configMap:
            name: maas-bin
            defaultMode: 0555
